---

driver:
  name: docker

platforms:
  - name: ROLE_NAME-xenial
    image: ubuntu:xenial
  - name: ROLE_NAME-bionic
    image: ubuntu:bionic

provisioner:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8 molecule/
dependency:
  name: galaxy
  options:
    role-file: requirements.yml

scenario:
  name: default

verifier:
  name: testinfra
